### ISSUE TITLE
You looked at BakingPlate?

### ISSUE THREAD

**Issue by ProLoser** [hugodias/cakeStrap#1]
Just curious, there seems to be a lot of similarity and we're always looking to bolster contributors.

[BakingPlate](https://github.com/ProLoser/BakingPlate)

I was actually looking at setting up a build with Twitter's Bootstrap, I've just been really busy.

**Comment by hugodias** [comment]
Hey man, how u doing? This project aims only to create an authentication system already with the layout of the twitter bootstrap! From what I understand, your project is a plugin for the bootstrap twitter right? It's really nice, but I think the proposal of 'cakeStrap' is a little different. Thanks for the tip!

**Comment by ProLoser** [comment]
Our project originally started as a way to implement the HTML5 boilerplate
but then it expanded into a Kickstarter the plugIn. Essentially it will
allow you to build most of your common utilities you want from the get-go
but it also allows you to it add other libraries too.
We don't have a Twitter bootstrap in the system and we've also been looking
at having it come bundled with authentication built in. What we have now
however degrade so that you can remove it and implement your own
authentication if you just want the rest of the features.

You might want to take another look because it lets you build a new app
with whatever Combination of plug-ins and templates that you like
On May 28, 2012 11:11 AM, "hugodias" <
reply@reply.github.com>
wrote:

**Comment by ProLoser** [comment]
For instance, if you took what was unique to your build (the view layer and webroot), threw it into a bake template and theme, you'd get almost the same functionality you already have, except people would be able to generate more sections too into the Twitter Bootstrap.

There are quite a few other notes and reasons you may want to join our efforts, as we'd be able to help you turn this into a reusable plugin in many other ways, and you wouldn't lose any of the functionality you are currently trying to provide.

**Comment by hugodias** [comment]
I glanced at the bottom and the project is really very interesting. I'll do the fork and start exploring. I'll start trying to improve the front end, perhaps putting more funciinalidades into the html5 form helper.

**Comment by ProLoser** [comment]
A start would be turning your view later into a theme and making bake
templates. That way someone could make the User CRUD and any other sections
too. A theme would be able to hold your custom webroot and home.
On May 29, 2012 1:48 AM, "hugodias" <
reply@reply.github.com>
wrote:
