### ISSUE TITLE
Plugin Instalação.

### ISSUE THREAD

**Issue by fadonascimento** [hugodias/cakeStrap#15]
Acha que seria interessante criar um plugin para facilitar a instalação, criar o database.php, criar a tabela users, etc?

**Comment by hugodias** [comment]
@fadonascimento você diz um script ?

**Comment by fadonascimento** [comment]
Não um plugin mesmo passo a passo, fiz um pull request, do plugin para exemplo, seria interessante também usar o PhpAcl, ele é bem simples para usar e poderia fazer um metodo no helper para que todo link passasse por ele e verificaria se tem acesso a essa action, vou montar um exemplo.
