### ISSUE TITLE
Correct title

### ISSUE THREAD

**Issue by dereuromark** [hugodias/cakeStrap#27]
The headline is clearly a lie (or can easily be misunderstood):
"CakeTrap is a HTML5 CakePHP 3.0 Bootstrap !"

It is a CakePHP2.x bootstrap (not 3.x).
Also CakeTrap != CakeStrap

So this would be better:
"CakeStrap is a bootstrap for CakePHP - HTML5 CakePHP2.x Bootstrap3.0!"

**Comment by hugodias** [comment]
Thanks @dereuromark ! Already fixed :)
