### ISSUE TITLE
Delete feature not working

### ISSUE THREAD

**Issue by gmlunardi** [hugodias/cakeStrap#28]
Hello,
I can not delete a user. In view folder "Users" index.ctp has: 'data-uid' => $user['User']['id'], 'data-uname' => $user['User']['username'] on line 39. It seems that user's id does not pass to delete method.

**Comment by hugodias** [comment]
Hello @gmlunardi , the delete feature is working just fine here. Is there any JS error? This feature uses Bootstrap modal to show a confirmation message before delete the user, and in this modal there will be the delete button, a red one. This modal it's been showing for you?

**Comment by gmlunardi** [comment]
@hugodias, tkanks! The bootstrap modal confirmation message is working for me, but I receive an exception that user can not be deleted. I think the id is not beeing passed to the delete method.

**Comment by hugodias** [comment]
Can you copy and paste here the exactly error or a print screen?

**Comment by gmlunardi** [comment]
yes, here is the image:

![modal error](https://cloud.githubusercontent.com/assets/5599767/2930579/36a12a1c-d798-11e3-9fb9-18cd2181b74a.png)

**Comment by abhayapatel** [comment]
I am facing the same problem. is there any solution to it?

**Comment by hugodias** [comment]
hey @abhayapatel and @gmlunardi , make sure that this script (https://github.com/hugodias/cakeStrap/blob/master/app/webroot/js/users/index.js) it's been loaded.  you may want to move this event(https://github.com/hugodias/cakeStrap/blob/master/app/webroot/js/users/index.js#L23) to a main script, so it will work in every page

**Comment by abhayapatel** [comment]
Thanks @hugodias, actually we need to include both "lib/jquery" and "users/index" in the default.ctp file which is not there in you code. Thanks again.

**Comment by gustavocp** [comment]
Thank you guys, it's working now. 

Change this line:
https://github.com/hugodias/cakeStrap/blob/master/app/View/Layouts/default.ctp#L47

to 
<?php echo $this->Html->script(array('lib/bootstrap.min', 'src/scripts.js', 'users/index.js')); ?>

**Comment by zhaff** [comment]
Hi guys,

You can find the fix here:
https://github.com/zhaff/cakeStrap/commit/7d43660bf08d82eec87e226d0f36420b81ec5156

**Comment by hugodias** [comment]
Hey guys. The Pull Request #33 from @zhaff fixed it. Thanks!
