### ISSUE TITLE
Is there a way to bypass the install procedure?

### ISSUE THREAD

**Issue by murparreira** [hugodias/cakeStrap#29]

**Comment by hugodias** [comment]
Yes, you'll have to install it manually:
- Rename the `app/Config/config.php.install` file to `app/Config/config.php` and still in this file change the $config['Application']['status'] to **true**
- Rename the `app/Config/database.php.default` file to `app/Config/database.php` and configure your database credentials
- Create the users table in your database with this Schema: https://github.com/hugodias/cakeStrap/blob/master/app/Config/Schema/schema.php

**Comment by murparreira** [comment]
Thanks dude.
