### ISSUE TITLE
tmp folder not found.

### ISSUE THREAD

**Issue by joshdcid** [hugodias/cakeStrap#3]
Hi i'm getting this error: /Users/joshdcid/Sites/public_html/rcrsys/app/tmp/cache/ is not writable [CORE/Cake/Cache/Engine/FileEngine.php, line 336]

But i couldn't find the folder, what can i do? do i copy a cakephp tmp folder or...?

Well thanks for the help!

**Comment by hugodias** [comment]
Hello @joshdcid i just found this error today too ! You need to create this folder in tmp folder. I'll fix this bug today !

**Comment by hugodias** [comment]
But i strongly recommend that you copy this folder and all subfolders from Official cakephp repo ! It's the same structure...

**Comment by hugodias** [comment]
Done. Included in my last commit https://github.com/hugodias/cakeStrap/commit/40003386f3c12a56dd914b96572c1c8ae273d204
