### ISSUE TITLE
Adding page-specific Javascript to each view in CakePHP

### ISSUE THREAD

**Issue by sirhaplo** [hugodias/cakeStrap#4]
Hi, i'm a fan of your work, well done.

In my projects i used a best-practice that i've found here :
http://stackoverflow.com/questions/1425084/adding-page-specific-javascript-to-each-view-in-cakephp

It simply add a css and js page-specific load in the default.ctp.
So every page has a ctp in his view directory and a js and a css in the right directory under webroot.

its so easy :
<?php
    if (is_file(WWW_ROOT . 'css' . DS . $this->params['controller'] . '.css')) {
        echo $html->css($this->params['controller']);
    }
    if (is_file(WWW_ROOT . 'css' . DS . $this->params['controller'] . DS . $this->params['action'] . '.css')) {
        echo $html->css($this->params['controller'] . '/' . $this->params['action']);
    }
?>

This would be a great upgrade to your project

**Comment by hugodias** [comment]
Thanks for the tip @sirhaplo ! I'll test this environment in my current project and I'll see how it goes ! Btw you can always submit your code by doing a pull request. :)

**Comment by sirhaplo** [comment]
You are right. It was my first approach to github, and i missclicked ;)

**Comment by hugodias** [comment]
Hey @sirhaplo i just included this automatic load of js and css files in cakeStrap. Check this out https://github.com/hugodias/cakeStrap/commit/dfcf0023c1e9a51e873ffb431742f33384ef3dc0
