### ISSUE TITLE
Unknown Variable in app/View/Emails/html/remember_password.ctp

### ISSUE THREAD

**Issue by leegraham** [hugodias/cakeStrap#7]
In app/View/Emails/html/remember_password.ctp I'm getting an unknown variable error...

For resetting your password, visit the link below:

Notice (8): Undefined variable: hash [APP/View/Emails/html/remember_password.ctp, line 3]
Code Context
        ob_start();

```
    include $this->__viewFile;
```

$viewFile = '/app/View/Emails/html/remember_password.ctp'
$dataForView = array(
    'content' => ''
)
$content = ''
include - APP/View/Emails/html/remember_password.ctp, line 3
View::_evaluate() - CORE/Cake/View/View.php, line 920
View::_render() - CORE/Cake/View/View.php, line 883
View::render() - CORE/Cake/View/View.php, line 475
CakeEmail::_renderTemplates() - CORE/Cake/Network/Email/CakeEmail.php, line 1551
CakeEmail::_render() - CORE/Cake/Network/Email/CakeEmail.php, line 1418
CakeEmail::send() - CORE/Cake/Network/Email/CakeEmail.php, line 1057
UsersController::remember_password() - APP/Controller/UsersController.php, line 207
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 485
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 186
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 161
[main] - APP/webroot/index.php, line 92
Register new password
If you did not request a new password, please ignore this email.

**Comment by hugodias** [comment]
@leegraham Your controller probably is not generating the hash for user remember password ( https://github.com/hugodias/cakeStrap/blob/master/app/Controller/UsersController.php#L191 ) . Please debug this variable before send email and tell me what it contains.

**Comment by leegraham** [comment]
@hugodias Hey man, thanks for the quick response! Right after Line 191 I inserted the following code: Debugger::dump($hash);

I re-ran users/remember_password form. It dispatched the email and on the page it displayed the debug info containing my hash. So the hash is being properly generated.

It doesn't appear to be passing the $hash variable from the form to the email. As an experiment, I created a variable $hash = '123'; in the email template and it worked without any issue.

Does any of this ring a bell?

**Comment by hugodias** [comment]
Hummmm ...  I don't understand why's that. If you have this line (https://github.com/hugodias/cakeStrap/blob/master/app/Controller/UsersController.php#L209) in your code, this must work properly, as you can see here: (http://book.cakephp.org/2.0/en/core-utility-libraries/email.html#sending-templated-emails)

**Comment by leegraham** [comment]
100% my fault. I deployed CakePHP on OpenShift.com causing 2 issues:

1) gmail wasn't working to send emails.
2) I had to comment out Line 208 and replace it with a hard code string

BTW... cakeStrap is frigging awesome! Thanks for the help
